### ISSUE TITLE
Duplicate git commits for SVN reference targets

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-ribose/github-migration-project#17]
The "SVN reference [...] has been migrated to Git Commit ..." messages in comments / commit messages point to git commits that are not on any branch. These seem to be duplicates of commits that are on branches.
E.g., https://github.com/ietf-svn-conversion/ietfdb/commit/bff3a64042c14b68c8603df9fe19b777f132e8e4 includes

> Note: SVN reference [19555] has been migrated to Git commit [b96aaeb](https://github.com/ietf-svn-conversion/ietfdb/commit/b96aaebedf75b04709a22c2be66a741538eedf2b)

Issue https://github.com/ietf-svn-conversion/ietfdb/issues/3414 has the same note. That commit is labeled with legacy-id [19555] but is not on any branch.

One of the parent commits of https://github.com/ietf-svn-conversion/ietfdb/commit/bff3a64042c14b68c8603df9fe19b777f132e8e4 is https://github.com/ietf-svn-conversion/ietfdb/commit/182b7d69d6a5b64b20d50887419e158c49b96419. This is also legacy-id [19555], and I believe is identical to the other commit but *is* on a branch.

Is it possible for the SVN references to point at commits on the branch history instead of duplicates?

**Comment by HassanAkbar** [comment]
This is happening because of a circular dependency in commits while running `git-filter-repo`.
The issue occurs when:
1. A commit message is updated with the link of another commit. e.g added reference in https://github.com/ietf-svn-conversion/ietfdb/commit/1dff80218711f3530e98d2cfb6e7fd20994f0441 to https://github.com/ietf-svn-conversion/ietfdb/commit/c613c09f2bb4a1ff37fab0480935792b777717c0
2. This updates the SHA hash of the commit we updated in step 1. i.e. https://github.com/ietf-svn-conversion/ietfdb/commit/1dff80218711f3530e98d2cfb6e7fd20994f0441
3. Due to above, the SHAs of all ancestor commits in the tree are also updated.
4. This also updates the SHA of the commit whose link was added in the message in Step 1. i.e https://github.com/ietf-svn-conversion/ietfdb/commit/c613c09f2bb4a1ff37fab0480935792b777717c0 now becomes https://github.com/ietf-svn-conversion/ietfdb/commit/a92e052e174517b897da1985f73ae63d13874d16.
5. Now https://github.com/ietf-svn-conversion/ietfdb/commit/c613c09f2bb4a1ff37fab0480935792b777717c0 is removed from branch but as this commit is referred in the message of https://github.com/ietf-svn-conversion/ietfdb/commit/1dff80218711f3530e98d2cfb6e7fd20994f0441, its not deleted from Github (stays there as a duplicate commit.)

So now we have duplicate commits and the commit that is not in the tree shows the message that `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`.

@ronaldtse  I don't think we can use `git-filter-repo` here. What do you think we should do here?

**Comment by ronaldtse** [comment]
It looks like the problem in Step 3. The "ancestor commits" should not have been updated if we change a commit message -- only "descendent commits" should be updated.

I don't understand why there is a circular dependency here, because:
1. A newer commit should always refers back to an older commit.
2. When we change the newer commit, only "descendants" should be updated, not "ancestors".

When we call `git-filter-repo`, we should not change any ancestor commit of the commit to be updated.

**Comment by ronaldtse** [comment]
Maybe the `git-filter-repo` `--message-callback` argument is useful:

https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html#CALLBACKS

```
--message-callback <function_body>
Python code body for processing messages (both commit messages and tag messages); see [CALLBACKS].
```

e.g.
```sh
git-filter-repo --message-callback '
  if b"Signed-off-by:" not in message:
    message += b"\nSigned-off-by: Me My <self@and.eye>"
  return re.sub(b"[Ee]-?[Mm][Aa][Ii][Ll]", b"email", message)'
```

**Comment by HassanAkbar** [comment]
@ronaldtse 
Yes you were right, there is no circular dependency here. 

> Maybe the git-filter-repo --message-callback argument is useful:

I was already using `--message-callback` to update the messages but the references were not updating so I looked into the code of `git-filter-repo` and found that it first tries to:
1. `Fix the references` 
2. Execute the `message-callback`

Because we were adding the references in the callback they were not getting updated.

I tweeked the source code of `git-filter-repo` and was able to fix the issue. 
I changed the order of the 2 operations (mentioned above) so it first executes the `message-callback` now and then fixes the references.

 I ran it on the `ietfdb repo`. Now the results seems correct as you can check in the screenshot below:

<img width="1440" alt="Screenshot 2021-12-02 at 6 10 13 PM" src="https://user-images.githubusercontent.com/5301572/144429907-cf214559-9fa9-4434-bd2b-9634cd30e6cb.png">

**Comment by HassanAkbar** [comment]
@ronaldtse opened a PR for this here -> https://github.com/newren/git-filter-repo/pull/306

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar !

**Comment by ronaldtse** [comment]
I don't think we will see `git-filter-repo` being merged/updated so fast anyway, so we should update our GHA workflows to use the forked `git-filter-repo`. Will create a new task for it.

**Comment by HassanAkbar** [comment]
Fixed in the linked PR.
