### ISSUE TITLE
datatracker migration splits the tzaware branch up oddly

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/github-migration-project#26]
In the latest run /branch/tzaware in svn got split into one git branch per subdirectory. Why?
Can that be adjusted.

**Comment by ronaldtse** [comment]
@rjsparks that is probably due to configuration in the migration script. Let us investigate how.

**Comment by HassanAkbar** [comment]
It is due to the configuration of reposurgeon. I was looking at the [ietfdb repo](https://svn.ietf.org/svn/tools/ietfdb/branch/) and it looks like that inside the `branch` folder there are some folders that are branches e.g [`tzaware`](https://svn.ietf.org/svn/tools/ietfdb/branch/tzaware/), but some of them looks like folders containing multiple branches e.g [`branch/akayla/irsg/`](https://svn.ietf.org/svn/tools/ietfdb/branch/akayla/irsg/).

I want to confirm is there a convention to figure out that a folder is a single branch or contains multiple branches?

**Comment by rjsparks** [comment]
There are conventions, but they changed over time, and there are lots of exceptions to the conventions.

You can generally tell by inspection, looking at the thing you're unsure about and seeing if it just has a bunch of directories that don't look like the project structure (the ietf directory is a big key) or if it has non-directory files.

attic/ contains individual branches directly
branch/ contains individual branches at several levels it's the most messy in the tree:
- There are a few groups of similar things under branch/
  - These are directly branches: 2.00, 3.00, 3.xx-trunk, auth, idsubmit, iesg-datatracker, new, tzaware
  - These are irregular and have branches nested inside them in unusual ways:
    - branch/akayla/irsg contains branches
    - elft, hawk, and csky should be each treated as a branch (but they contain separate projects)
    - legacy is an unusual thing that should be treated as a branch
  - the rest are regular - each directory contains branches (e.g. branch/iola/team-support is a branch)
  
personal/  is regular and should not have surprises. It has a directory per person (like personal/rjs/) and that directory contains branches.

sprint/  contains many branches grouped by sprint number(at sprint/73/rjs for example). There are two irregular files in sprint/ itself (a couple of scripts) that should be preserved in a branch named sprint/

tags/ contains tags which are branches, with the exception of these special directories, which themselves contain branches
  - tags/dev
  - tags/amsl
  - tags/id2xml
  - tags/idnits3

**Comment by HassanAkbar** [comment]
I have incorporated most of the stuff mentioned above.

There is just one small issue related to the `sprint` folder. We can not move these scripts in a branch because of two 
reasons:
1. GitHub does not allow creating a branch name `sprint` if a `sprint/*` branch exists. So, its not possible to create sprint branch due to presence of branches like `sprint/73/rjs`.
2. Reposurgeon converts folders to branches. So, we can't move scripts to a branch.

What we can do is either of the following:
- Move the scripts in a folder in `svn`. In this way there will be no conflict and the folder name can become the branch name.
- Add the scripts after the Reposurgeon migration in a branch name other than `sprint` manually.
I am inclined in moving these scripts to a folder in `svn`. If that does not creates a problem at your end?

**Comment by rjsparks** [comment]
They are now in a subdirectory of sprints/ ( sprints/sprintscripts) which can be made into its own branch

**Comment by ronaldtse** [comment]
@HassanAkbar I believe this issue is completed, right?

**Comment by HassanAkbar** [comment]
> @HassanAkbar I believe this issue is completed, right?

Yes, this can be closed now.
